### ISSUE TITLE
Bugs on 'http' and 'https' files.

### ISSUE THREAD

**Issue by sanjay-bytecode** [sm0k3net/GetMeProxy.com#1]
I have implemented this project on my server and follow all step as explain in this repository. But no active proxies shown on my website and no any proxies insert automatically. On debugged the code I found that on http (config/) file there so many bugs .I attach my screenshot.
https://screenshots.firefox.com/U86PbGYMrkG9bJ6L/bytecodetechnologies.co.in**
My website link is 
http://bytecodetechnologies.co.in/proxy-list/config/http.php

**Comment by sm0k3net** [comment]
Hi, do you run your server on PHP verion 7 or lower ?
Problems can be caused by new PHP version so need confirmation.

**Comment by sanjay-bytecode** [comment]
Currently running my server on PHP 5.1 version. This project does not support PHP 7 or latest version.

**Comment by sm0k3net** [comment]
Can you provide web server logs to info@sm0k3.net ?
Also, can try to check the problem on your server, but I will be available a bit later, 21:00 - 22:00 GMT +3

**Comment by sanjay-bytecode** [comment]
I sent you a mail on info@sm0k3net . 
I have checked many times my code and find bugs on 'http' and other files on config folder.

**Comment by sm0k3net** [comment]
The problem was in proper files rights (all files in /config/ folder requires at least 755 rights to execute).
Also please review all the files and update path where required for actual one (I mean full path to the files and URLs) as it somewhere may try to use old paths or links.
![proxy-works](https://user-images.githubusercontent.com/3437210/44199011-9f2dd400-a14b-11e8-8e98-406e8435f35a.PNG)

**Comment by sanjay-bytecode** [comment]
Wow ! Amazing , It's working fine . Thank you sm0k3.net . I have review all codes and correct all path with actual one.
